name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: de.eldoria.bloodnight.core.BloodNight
website: www.spigotmc.org/resources/80805/
api-version: 1.13

commands:
  bloodnight:
    description: lul
    usage: ""
    aliases:
      - bnight