name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: de.eldoria.bloodnight.core.BloodNight
website: https://www.spigotmc.org/resources/85095/
api-version: 1.16
softdepend:
  - Multiverse-Core
  - Hyperverse

commands:
  bloodnight:
    description: Main Blood Night command.
    usage: "/boodnight help"
    aliases:
      - bnight
      - bn