name: ${name}
description: ${description}
author: Hadde
version: ${version}
main: de.eldoria.bloodnight.core.BloodNight
website: ${url}
api-version: 1.16
softdepend:
  - Multiverse-Core
  - Hyperverse
  - MythicMobs
  - PlaceholderAPI

commands:
  bloodnight:
    description: Main Blood Night command.
    usage: "/bloodnight help"
    aliases:
      - bnight
      - bn