name: ${project.name}
description: ${project.description}
author: Hadde
version: ${project.version}
main: de.eldoria.bloodnight.core.BloodNight
website: https://www.spigotmc.org/resources/85095/
api-version: 1.16
depend:
  - EldoUtilities
softdepend:
  - Multiverse-Core
  - Hyperverse
  - MythicMobs
  - PlaceholderAPI

commands:
  bloodnight:
    description: Main Blood Night command.
    usage: "/bloodnight help"
    aliases:
      - bnight
      - bn